### ISSUE TITLE
t05_maximization_bias 

### ISSUE THREAD

**Issue by codebro634** [automl-edu/RL_lecture#22]
![pic](https://user-images.githubusercontent.com/55958538/140537340-a211f729-bc47-4d92-9f9f-7b4a581f2d8c.png)

Am I mistaken or must the update formula on this slide be adjusted like that? If we would not do that we would still be facing the problem, that we are approximating the expectance over a maximum.

**Comment by mlindauer** [comment]
Hi, 

Thanks for pointing this out. You are completely right. 
For more details on the topic, please also see the paper: https://proceedings.neurips.cc/paper/2010/file/091d584fced301b442654dd8c23b3fc9-Paper.pdf

Could you please submit a PR to fix it.

Best,
Marius

**Comment by codebro634** [comment]
Hey,
I just created the pull request.
Cheers,
Robin
