### ISSUE TITLE
VFA: Temporal Difference. Questions concerning slides

### ISSUE THREAD

**Issue by codebro634** [automl-edu/RL_lecture#27]
![img](https://user-images.githubusercontent.com/55958538/141506844-2ab16236-f343-48ae-9e28-1ba252f8f60e.png)
Im having trouble understanding this update formula. If we want to minimize the given mean squared error why dont we travel in the direction of gradient of J(w)? On a sidenote: Are we supposed to ask question like this here or should we do that in mattermost?

**Comment by mlindauer** [comment]
Thanks for asking. You should see the \hat{V}^\pi as the "old" approximation for what will happen in the "future", and \hat{V} with \vec{w} as the one we want to update. So, \hat{V}^\pi is treated as a constant and therefore, not important for the gradient.
In general, it is best to ask such things in the exercise or lecture. But you can also use this channel.

**Comment by codebro634** [comment]
![loss](https://user-images.githubusercontent.com/55958538/142283240-346c2ff9-d3e1-4c4a-88fc-4257449e22b1.png)
First of all thank you for your reply! That still doesn't make everything clear for me though. I will just state my train of thought and maybe you can spot the error in my line of argumentation: Our ultimate goal is to minimize the function I linked under this comment. But in this specific scenario on the slide we only have access to a limited set of data pairs. So we resort to supervised learning. In a supervised learning setting we want to minimize some loss-function, but in order to perform supervised learning we require that loss function to be computable given some weights and our data pairs. That's why we cant just use a loss-function that contains the real V^{\pi}. As a workaround we substitute V^{\pi} with our biased estimation using V^{\hat}^\pi. Ok, now we have defined our loss function, which is exactly the one on the slides J(w) and we minimize that by going into the direction of the gradient. And since we defined J(w) to be our loss-function we can't just treat parts of it as constant or else we wouldn't be minimizing J(w). And if we aren't minimizing J what are we minimizing then and why don't we try to minimize J instead? For me intuitively it would make sense to minimize J(w) (i.e. going in the direction of the gradient I computed) because that way we are making most of our limited scope which is our set of data pairs. So we are adapting as much as possible to all we know.
